# Generated by Django 5.1.2 on 2024-12-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("traits", models.TextField()),
                ("image", models.ImageField(upload_to="dog_images/")),
            ],
        ),
    ]
