# Generated by Django 5.1.2 on 2024-12-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_quizresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="image",
            field=models.ImageField(upload_to="static/"),
        ),
    ]
