# Generated by Django 5.1.2 on 2024-12-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_dog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog", name="image", field=models.CharField(max_length=255),
        ),
    ]
