# Generated by Django 5.1.2 on 2024-12-25 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_dog_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="quizresponse", name="submitted_at",),
        migrations.AlterField(
            model_name="quizresponse",
            name="activity_level",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="quizresponse",
            name="children",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="quizresponse",
            name="grooming",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="quizresponse",
            name="living_space",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="quizresponse",
            name="time_dedication",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="AdoptedDog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.dog"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedDog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.dog"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
