# Generated by Django 5.1.2 on 2024-12-25 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_quizresponse_submitted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quizresponse",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="adopteddog",
            name="dog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adopted_by_users",
                to="main.dog",
            ),
        ),
        migrations.AlterField(
            model_name="adopteddog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adopted_dogs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="saveddog",
            name="dog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by_users",
                to="main.dog",
            ),
        ),
        migrations.AlterField(
            model_name="saveddog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_dogs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
